#!/bin/sh

gcc -o compress -I ../ts -lbz2 compress.c

for I in ts4200 ts4500 ts4700 ts7670 ts7700 ts4800 ts8100 ts8160 ts8200 ts8390 ts8820 ts8900 ts9490 tsdio24 tsrelay8; do
    ./compress ${I}.dioctl.config $1 > ../ts/${I}_dioctl_config.c
done
rm -f dioctl_config dioctl_map dioctl_map.c compress

